name: I’m having trouble with Odyc
description: Have a problem? It might be a bug! Create a report to help us improve.
labels: [bug]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: 'Optional: Steps to reproduce the behavior.'
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See an error
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: 'Optional: A clear and concise description of what you expected to happen.'
  - type: input
    id: repro-url
    attributes:
      label: Reproduction URL
      description: 'Optional: The URL to the **public** repository for the reproduction. _[parser:url]_'
      placeholder: e.g. https://github.com/...
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: 'Optional: If applicable, add screenshots to help explain your problem.'
